# ?????? ?-Supabase (Postgres)
spring.datasource.url=jdbc:postgresql://db.xixwqnunyymwprpxetrp.supabase.co:5432/postgres?ssl=true
spring.datasource.username=postgres
spring.datasource.password=Brachi14082006
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update